name: Deploy to Strato via SFTP

on:
  push:
    branches:
      - main  # Oder 'master', je nachdem wie dein Haupt-Branch hei√üt

jobs:
  deploy:
    name: Upload Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Strato
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22

